baseURL: https://pham-viet-hung-2.netlify.app/
languageCode: en-us
title: Portfolio dsb2023 website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
    subtitle: |-
    #  A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #  AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Pham Viet Hung's Data Analytics Portfolio
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        #street: 62 Balcombe Street
        #title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hpham.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7377 936 195
        title: Mobile
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    enable: yes
    quicklinks:
    #  - alt: PORTFOLIO WEBSITE
    #    text: 'Design: '
    #    url: https://pham-viet-hung.netlify.app/
    social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
    #  - icon: fa-github
    #    label: GitHub
    #    url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/viet-hung-pham/
  image: ''
  name: Pham Viet Hung
  navigation:
    button1:
      - name: CV/Resume
        url: CV.pdf
    #button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: London Business School
        url: blogs/LBS
      - name: Operational Intelligence
        url: blogs/OI
      - name: Expertise Network
        url: blogs/EN
      - name: Mass Shooting Analysis
        url: blogs/MSA
    menu: Menu
    subtitle: PORTFOLIO WEBSITE
    title: PHAM VIET HUNG
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: My story in strategy consulting and London Business School
        title: Introduction
        url: blogs/LBS
      - image: pic02.jpg
        subtitle: Built a  
        title: Operational Intelligence
        url: blogs/OI
      - image: pic03.jpg
        subtitle: Support NHS
        title: Expertise Network
        url: blogs/magna
      - image: spices.jpg
        subtitle: LBS Coursework - Analysis of Dow Jones Industrial Average (DJIA)
        title: Risk-Return of DJIA Stock
        url: blogs/RR
      #- image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
      #  title: Consequat
      #  url: blogs/ipsum
      #- image: pic06.jpg
      #  subtitle: Feugiat Amet Tempus
      #  title: Etiam
      #  url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: no
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
